version: '2'
services:
  php56:
    build:
      context: .
      dockerfile: Docker/PHP5.6/Dockerfile
    volumes:
      - ./src:/app/src
      - ./spec:/app/spec
  php70:
    build:
      context: .
      dockerfile: Docker/PHP7.0/Dockerfile
    volumes:
      - ./src:/app/src
      - ./spec:/app/spec
  php72:
    build:
      context: .
      dockerfile: Docker/PHP7.2/Dockerfile
    volumes:
      - ./src:/app/src
      - ./spec:/app/spec
  php74:
    build:
      context: .
      dockerfile: Docker/PHP7.4/Dockerfile
    volumes:
      - ./src:/app/src
      - ./spec:/app/spec
